AWSTemplateFormatVersion: 2010-09-09
Description: |
  Build a phonebook app with EC2,RDS and Load Balancer
Parameters:
  VpcId:
    Description: VPC where application is deployed
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Subnets for load balancing
    Type: List<AWS::EC2::Subnet::Id>


Resources:

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Port: 80
      Protocol: HTTP
      LoadBalancerArn: !Ref Loadbalancer

  Loadbalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - !GetAtt LbSecurityGroup.GroupId
      Subnets: !Ref Subnets
      Type: application
 

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 10
      UnhealthyThresholdCount: 3
      TargetType: instance
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId

  
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS # Required
      GroupName: AllowMySqlAccess
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          Description: create sg using cfn for RDS
          FromPort: 3306
          IpProtocol: tcp
          ToPort: 3306
      VpcId: !Ref VpcId


    LbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow access to LB # Required
        GroupName: AllowHTTPAccess
        SecurityGroupIngress: 
          - CidrIp: 0.0.0.0/0
            Description: create sg using cfn for lb 
            FromPort: 80
            IpProtocol: tcp
            ToPort: 80
        VpcId: !Ref VpcId
    

  RDSDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: "8.0.36"
      DBInstanceIdentifier: phonebook-instance
 
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      PubliclyAccessible: true
      MultiAZ: false
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod: 0
      Port: "3306"

      VPCSecurityGroups: 
        - !GetAtt DbSecurityGroup.GroupId   

      MasterUsername: '{{resolve:ssm:/my-clarusway/db/user}}'
      MasterUserPassword: '{{resolve:ssm:/my-clarusway/db/password}}'
      DBName: '{{resolve:ssm:/my-clarusway/db/dbname}}'
      
     
      # DBSubnetGroupName: "String"   
  
# Outputs: