AWSTemplateFormatVersion: 2010-09-09
Description: create static website for kittens crousel
Resources:
  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSh and HTTP" # Required
      GroupName: "KittensSecGroup"
      SecurityGroupIngress: #Ingress inbound rules
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

  LogicalID:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: Ali-test-kitten-web1
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      KeyName: ec2-li-linus
      SecurityGroupIds:
        - !GetAtt rSecurityGroup.GroupId
      UserData: "String"
