AWSTemplateFormatVersion: 2010-09-09
Description: create static website for kittens crousel
Resources:
  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSh and HTTP" # Required
      GroupName: "KittensSecGroup"
      SecurityGroupIngress: #Ingress inbound rules
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: Ali-test-kitten-web
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      KeyName: ec2-ali-linus
      SecurityGroupIds:
        - !GetAtt rSecurityGroup.GroupId
      UserData:
        Fn::Base64: 
          |
            #! /bin/bash -x

            yum update -y
            yum install httpd -y

            cd  /var/www/html

            FOLDER=https://raw.githubusercontent.com/myhelper65/my-repository/main/101-kittens-carousel-static-website-ec2/static-web

            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg

            systemctl start httpd
            systemctl enable httpd

Outputs:

  WebURL:
    Description: URL for website
    Value: !Join [ "", ["http://", !GetAtt rWebServer.PublicDnsName ] ]
